name: vamp_inst_paper
dependencies:
  - conda-forge::astropy=5.3.4
  - conda-forge::numpy=1.24.0
  - conda-forge::pip=21.0.1
  - conda-forge::python=3.9
  - pip:
      - matplotlib==3.4.3
      - proplot==0.9.7
      - scikit-image==0.22.0
      - -e /Users/mileslucas/dev/python/scexao_etc